---@class TransientState
---@field uiVars UiVars

---@class UiVars
---@field BASE_OBJ_SCALE Vector3
---@field QUALITY number
--
---@field UI_HEIGHT number
---@field UI_WIDTH number
--
---@field SPACING number
---@field SPACING_S number
--
---@field HEADER_PADDING number
--
---@field CONFIG_UI_PARAMS ConfigUiParams
